# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class Invoker:
        name: str
        type: str
        url: str
    class Resolver:
        name: str
        type: str
        url: str
    class Workflow:
        name: str
        qualifier: str
        type: str

